version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    volumes:
      - ./backend:/app
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/mydatabase
    depends_on:
      - db

  frontend:
    build:
      context: .
      dockerfile: ./MedTrack/Dockerfile
    volumes:
      - ./MedTrack:/app
    ports:
      - "3000:80"
    depends_on:
      - backend

  db:
    image: postgres:13
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"